// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq6Wc9tjemJ8RudjqsJrJTCkxoB_dxuHw',
    appId: '1:116725106228:web:5bacea64bfcaf9cd4d2c61',
    messagingSenderId: '116725106228',
    projectId: 'qorai-99b6e',
    authDomain: 'qorai-99b6e.firebaseapp.com',
    storageBucket: 'qorai-99b6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1HcMftJ9PtUz9RKlIZq_ySPP3w-74xg4',
    appId: '1:116725106228:android:44d925a88bddccf84d2c61',
    messagingSenderId: '116725106228',
    projectId: 'qorai-99b6e',
    storageBucket: 'qorai-99b6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSA9h9p-_pDSl40iDVeNvejA0Knqu0lnE',
    appId: '1:116725106228:ios:35ad878278618ca14d2c61',
    messagingSenderId: '116725106228',
    projectId: 'qorai-99b6e',
    storageBucket: 'qorai-99b6e.firebasestorage.app',
    iosClientId:
        '116725106228-hs29d4gh4vldofj3a0aegfr4ootopr9q.apps.googleusercontent.com',
    iosBundleId: 'com.qorai.app',
  );
}
