// Generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJMUBkwXRRKqayyh1dlA0qovtVt1Gsl4I',
    appId: '1:510980756238:android:28418410181e915269fd5f',
    messagingSenderId: '510980756238',
    projectId: 'compair-99b6e',
    storageBucket: 'compair-99b6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJMUBkwXRRKqayyh1dlA0qovtVt1Gsl4I',
    appId: '1:510980756238:ios:9cc74b8f1e751da169fd5f',
    messagingSenderId: '510980756238',
    projectId: 'compair-99b6e',
    storageBucket: 'compair-99b6e.firebasestorage.app',
    iosClientId:
        '510980756238-369d7b3tst5k4aue0niai0g5tm7090c1.apps.googleusercontent.com',
    iosBundleId: 'com.compair.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJMUBkwXRRKqayyh1dlA0qovtVt1Gsl4I',
    appId: '1:510980756238:web:b21d1e3613561d7c69fd5f',
    messagingSenderId: '510980756238',
    projectId: 'compair-99b6e',
    storageBucket: 'compair-99b6e.firebasestorage.app',
  );
}
