// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_YqZli9PSPeCzYl2x9FBv5SYK-m0kpEg',
    appId: '1:510980756238:web:b21d1e3613561d7c69fd5f',
    messagingSenderId: '510980756238',
    projectId: 'compair-99b6e',
    authDomain: 'compair-99b6e.firebaseapp.com',
    storageBucket: 'compair-99b6e.firebasestorage.app',
    measurementId: 'G-D15CK4KT9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_etOaEBV0Bocx0IMvfP5UmrdyvMIp56Y',
    appId: '1:510980756238:android:28418410181e915269fd5f',
    messagingSenderId: '510980756238',
    projectId: 'compair-99b6e',
    storageBucket: 'compair-99b6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvJEqeJtgWHlh1FDevLxZx7Rmy9EI9vyE',
    appId: '1:510980756238:ios:9cc74b8f1e751da169fd5f',
    messagingSenderId: '510980756238',
    projectId: 'compair-99b6e',
    storageBucket: 'compair-99b6e.firebasestorage.app',
    iosBundleId: 'com.compair.app',
  );
}
